services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=nms
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # PostgreSQL Database for LangChain Checkpoints
  postgres:
    image: postgres:15
    container_name: langchain-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain_pass
      POSTGRES_DB: langchain
    volumes:
      - langchain_pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  # NMS Server
  nms:
    build:
      context: .
      dockerfile: nms/Dockerfile
    container_name: nms
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - MONGO_CONNECTION_URI=mongodb://root:password@db:27017/
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  # promptChart Server
  prompt-chart:
    build:
      context: .
      dockerfile: promptChart/Dockerfile
    container_name: prompt-chart
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - DB_URI=postgresql://langchain:langchain_pass@langchain-postgres/postgres?sslmode=disable
      - MONGO_CONNECTION_URI=mongodb://root:password@db:27017/
      - OPENAI_COMPAT_API_URL=http://host.docker.internal:1234/v1
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "4200:4200"
    depends_on:
      - postgres
      - mongodb
      - rabbitmq

  # API Server
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - MONGO_CONNECTION_URI=mongodb://root:password@db:27017/
      - REDIS_URL=${REDIS_URL}
      - LANGCHAIN_API_URL=http://prompt-chart:4200
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "2442:2442"
    depends_on:
      - mongodb
      - prompt-chart
      - rabbitmq

volumes:
  mongodb_data:
  langchain_pg_data:
