[project]
name = "common"
version = "0.5.1"
description = "Common Modules for the NMS applications"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Private :: Do Not Upload",
]
dependencies = [
    "fastapi>=0.121.0",
    "pydantic>=2.12.3",
    "pymongo>=4.15.3",
    "tzdata>=2025.2",
]

[project.optional-dependencies]
auth = [
    "bcrypt>=5.0.0",
    "clerk-backend-api>=3.3.1",
    "pyjwt>=2.10.1",
]
caching = [
    "hishel[httpx]==0.1.4",
    "redis>=7.0.1",
]
