[project]
name = "api"
version = "0.4.1"
description = "API Service to serve NMS Alerts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common[auth,caching,db]",
    "fastapi[standard]>=0.121.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "sse-starlette>=3.0.3",
]

[tool.uv.sources]
common = { path = "../common" }
